version: "3.8"

services:
  db:
    image: mysql:8
    ports:
      - 4409:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=docker
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker

  s3:
    container_name: demo_s3
    image: lphoward/fake-s3
    stop_grace_period: 0s
    ports:
      - "4569:4569"
    volumes:
      - s3-data:/fakes3_root:delegated

volumes:
  mysql-data:
  s3-data:
